package defpackage;

import java.util.Arrays;
import java.util.HashMap;

/* renamed from: yi3  reason: default package */
public final class yi3 {
    public int a;
    public final bj3 b;
    public final aj3 c;
    public final zi3 d;
    public final cj3 e;
    public HashMap f = new HashMap();

    /* JADX WARNING: type inference failed for: r0v0, types: [java.lang.Object, bj3] */
    /* JADX WARNING: type inference failed for: r0v1, types: [java.lang.Object, aj3] */
    /* JADX WARNING: type inference failed for: r0v2, types: [zi3, java.lang.Object] */
    /* JADX WARNING: type inference failed for: r0v3, types: [java.lang.Object, cj3] */
    public yi3() {
        ? obj = new Object();
        obj.a = 0;
        obj.b = 0;
        obj.c = 1.0f;
        obj.d = Float.NaN;
        this.b = obj;
        ? obj2 = new Object();
        obj2.a = -1;
        obj2.b = 0;
        obj2.c = -1;
        obj2.d = Float.NaN;
        obj2.e = Float.NaN;
        obj2.f = Float.NaN;
        obj2.g = -1;
        obj2.h = null;
        obj2.i = -1;
        this.c = obj2;
        ? obj3 = new Object();
        obj3.a = false;
        obj3.d = -1;
        obj3.e = -1;
        obj3.f = -1.0f;
        obj3.g = true;
        obj3.h = -1;
        obj3.i = -1;
        obj3.j = -1;
        obj3.k = -1;
        obj3.l = -1;
        obj3.m = -1;
        obj3.n = -1;
        obj3.o = -1;
        obj3.p = -1;
        obj3.q = -1;
        obj3.r = -1;
        obj3.s = -1;
        obj3.t = -1;
        obj3.u = -1;
        obj3.v = -1;
        obj3.w = 0.5f;
        obj3.x = 0.5f;
        obj3.y = null;
        obj3.z = -1;
        obj3.A = 0;
        obj3.B = 0.0f;
        obj3.C = -1;
        obj3.D = -1;
        obj3.E = -1;
        obj3.F = 0;
        obj3.G = 0;
        obj3.H = 0;
        obj3.I = 0;
        obj3.J = 0;
        obj3.K = 0;
        obj3.L = 0;
        obj3.M = Integer.MIN_VALUE;
        obj3.N = Integer.MIN_VALUE;
        obj3.O = Integer.MIN_VALUE;
        obj3.P = Integer.MIN_VALUE;
        obj3.Q = Integer.MIN_VALUE;
        obj3.R = Integer.MIN_VALUE;
        obj3.S = Integer.MIN_VALUE;
        obj3.T = -1.0f;
        obj3.U = -1.0f;
        obj3.V = 0;
        obj3.W = 0;
        obj3.X = 0;
        obj3.Y = 0;
        obj3.Z = 0;
        obj3.a0 = 0;
        obj3.b0 = 0;
        obj3.c0 = 0;
        obj3.d0 = 1.0f;
        obj3.e0 = 1.0f;
        obj3.f0 = -1;
        obj3.g0 = 0;
        obj3.h0 = -1;
        obj3.l0 = false;
        obj3.m0 = false;
        obj3.n0 = true;
        obj3.o0 = 0;
        this.d = obj3;
        ? obj4 = new Object();
        obj4.a = 0.0f;
        obj4.b = 0.0f;
        obj4.c = 0.0f;
        obj4.d = 1.0f;
        obj4.e = 1.0f;
        obj4.f = Float.NaN;
        obj4.g = Float.NaN;
        obj4.h = -1;
        obj4.i = 0.0f;
        obj4.j = 0.0f;
        obj4.k = 0.0f;
        obj4.l = false;
        obj4.m = 0.0f;
        this.e = obj4;
    }

    public final void a(ti3 ti3) {
        zi3 zi3 = this.d;
        ti3.e = zi3.h;
        ti3.f = zi3.i;
        ti3.g = zi3.j;
        ti3.h = zi3.k;
        ti3.i = zi3.l;
        ti3.j = zi3.m;
        ti3.k = zi3.n;
        ti3.l = zi3.o;
        ti3.m = zi3.p;
        ti3.n = zi3.q;
        ti3.o = zi3.r;
        ti3.s = zi3.s;
        ti3.t = zi3.t;
        ti3.u = zi3.u;
        ti3.v = zi3.v;
        ti3.leftMargin = zi3.F;
        ti3.rightMargin = zi3.G;
        ti3.topMargin = zi3.H;
        ti3.bottomMargin = zi3.I;
        ti3.A = zi3.R;
        ti3.B = zi3.Q;
        ti3.x = zi3.N;
        ti3.z = zi3.P;
        ti3.E = zi3.w;
        ti3.F = zi3.x;
        ti3.p = zi3.z;
        ti3.q = zi3.A;
        ti3.r = zi3.B;
        ti3.G = zi3.y;
        ti3.T = zi3.C;
        ti3.U = zi3.D;
        ti3.I = zi3.T;
        ti3.H = zi3.U;
        ti3.K = zi3.W;
        ti3.J = zi3.V;
        ti3.W = zi3.l0;
        ti3.X = zi3.m0;
        ti3.L = zi3.X;
        ti3.M = zi3.Y;
        ti3.P = zi3.Z;
        ti3.Q = zi3.a0;
        ti3.N = zi3.b0;
        ti3.O = zi3.c0;
        ti3.R = zi3.d0;
        ti3.S = zi3.e0;
        ti3.V = zi3.E;
        ti3.c = zi3.f;
        ti3.a = zi3.d;
        ti3.b = zi3.e;
        ti3.width = zi3.b;
        ti3.height = zi3.c;
        String str = zi3.k0;
        if (str != null) {
            ti3.Y = str;
        }
        ti3.Z = zi3.o0;
        ti3.setMarginStart(zi3.K);
        ti3.setMarginEnd(zi3.J);
        ti3.a();
    }

    public final Object clone() {
        yi3 yi3 = new yi3();
        zi3 zi3 = yi3.d;
        zi3.getClass();
        zi3 zi32 = this.d;
        zi3.a = zi32.a;
        zi3.b = zi32.b;
        zi3.c = zi32.c;
        zi3.d = zi32.d;
        zi3.e = zi32.e;
        zi3.f = zi32.f;
        zi3.g = zi32.g;
        zi3.h = zi32.h;
        zi3.i = zi32.i;
        zi3.j = zi32.j;
        zi3.k = zi32.k;
        zi3.l = zi32.l;
        zi3.m = zi32.m;
        zi3.n = zi32.n;
        zi3.o = zi32.o;
        zi3.p = zi32.p;
        zi3.q = zi32.q;
        zi3.r = zi32.r;
        zi3.s = zi32.s;
        zi3.t = zi32.t;
        zi3.u = zi32.u;
        zi3.v = zi32.v;
        zi3.w = zi32.w;
        zi3.x = zi32.x;
        zi3.y = zi32.y;
        zi3.z = zi32.z;
        zi3.A = zi32.A;
        zi3.B = zi32.B;
        zi3.C = zi32.C;
        zi3.D = zi32.D;
        zi3.E = zi32.E;
        zi3.F = zi32.F;
        zi3.G = zi32.G;
        zi3.H = zi32.H;
        zi3.I = zi32.I;
        zi3.J = zi32.J;
        zi3.K = zi32.K;
        zi3.L = zi32.L;
        zi3.M = zi32.M;
        zi3.N = zi32.N;
        zi3.O = zi32.O;
        zi3.P = zi32.P;
        zi3.Q = zi32.Q;
        zi3.R = zi32.R;
        zi3.S = zi32.S;
        zi3.T = zi32.T;
        zi3.U = zi32.U;
        zi3.V = zi32.V;
        zi3.W = zi32.W;
        zi3.X = zi32.X;
        zi3.Y = zi32.Y;
        zi3.Z = zi32.Z;
        zi3.a0 = zi32.a0;
        zi3.b0 = zi32.b0;
        zi3.c0 = zi32.c0;
        zi3.d0 = zi32.d0;
        zi3.e0 = zi32.e0;
        zi3.f0 = zi32.f0;
        zi3.g0 = zi32.g0;
        zi3.h0 = zi32.h0;
        zi3.k0 = zi32.k0;
        int[] iArr = zi32.i0;
        if (iArr == null || zi32.j0 != null) {
            zi3.i0 = null;
        } else {
            zi3.i0 = Arrays.copyOf(iArr, iArr.length);
        }
        zi3.j0 = zi32.j0;
        zi3.l0 = zi32.l0;
        zi3.m0 = zi32.m0;
        zi3.n0 = zi32.n0;
        zi3.o0 = zi32.o0;
        aj3 aj3 = yi3.c;
        aj3.getClass();
        aj3 aj32 = this.c;
        aj32.getClass();
        aj3.a = aj32.a;
        aj3.c = aj32.c;
        aj3.e = aj32.e;
        aj3.d = aj32.d;
        bj3 bj3 = yi3.b;
        bj3.getClass();
        bj3 bj32 = this.b;
        bj32.getClass();
        bj3.a = bj32.a;
        bj3.c = bj32.c;
        bj3.d = bj32.d;
        bj3.b = bj32.b;
        cj3 cj3 = yi3.e;
        cj3.getClass();
        cj3 cj32 = this.e;
        cj32.getClass();
        cj3.a = cj32.a;
        cj3.b = cj32.b;
        cj3.c = cj32.c;
        cj3.d = cj32.d;
        cj3.e = cj32.e;
        cj3.f = cj32.f;
        cj3.g = cj32.g;
        cj3.h = cj32.h;
        cj3.i = cj32.i;
        cj3.j = cj32.j;
        cj3.k = cj32.k;
        cj3.l = cj32.l;
        cj3.m = cj32.m;
        yi3.a = this.a;
        return yi3;
    }
}
